apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: geo-controller
  labels:
    name: geo-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: geo-controller
    spec:
      containers:
      - name: geo-cleanup
        image: gcr.io/atos-ohc-bigdata-demos/twitter-stream
        env:
        - name: PROCESSINGSCRIPT
          value: geo-cleanup
        # Change this to your pubsub topic
        - name: PUB_TOPIC
          value: projects/atos-ohc-bigdata-demos/topics/tweet_locations_neo
        - name: SUB_TOPIC
          value: projects/atos-ohc-bigdata-demos/topics/tweet_locations_geo
        # Change this to your project ID.
        - name: PROJECT_ID
          value: atos-ohc-bigdata-demos
        - name: ELASTIC_HOST
          value: 35.227.166.143
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: cpp